name: the_project_hariyal
description: A project by shanmukeshwar and gautham.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  firebase_auth:
  cloud_firestore:
  material_design_icons_flutter:
  geolocator:
  permission_handler:
  location:
  fluttertoast:
  multi_image_picker:
  shared_preferences:
  flutter_phoenix:
  firebase_storage:
  path_provider:
  flutter_absolute_path:
  date_time_format:
  catcher:
  image:
  geocoder:
  email_validator:
  flutter_spinkit:
  rxdart:
  photo_view:
  otp_text_field:
  workmanager:
  image_picker:
  flutter_money_formatter:
  flutter_data_stream_builder:
  provider:
  cached_network_image:
  share:
  image_cropper:
  flutter_swiper:
  lazy_load_scrollview:
  map_launcher:
  flutter_upi:
  firebase_messaging:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

fonts:
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/ubuntu.ttf
      - asset: assets/fonts/ubuntu_bold.ttf
      - asset: assets/fonts/ubuntu_bold_italic.ttf
      - asset: assets/fonts/ubuntu_italic.ttf
